name: patchcord

services:
  # NodeJS Backend
  api:
    build: 
      context: .
      target: dev
    ports:
      - ${SERVER_PORT:-3000}:3000
      - ${RTC_MIN_PORT:-10000}-${RTC_MAX_PORT:-10100}:10000-10100/udp
      - ${RTC_MIN_PORT:-10000}-${RTC_MAX_PORT:-10100}:10000-10100/tcp
    volumes:
      - .:/app
      - /app/node_modules
    restart: no
    networks:
      - backend
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
        
  # MongoDB
  mongodb:
    image: mongo:4.4
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./.data/db:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Redis
  redis:
    image: redis:8.4
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ./.data/cache:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Minio 
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data/minio --console-address ":${MINIO_CONSOLE_PORT:-9090}"
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9090}:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - './.data/s3:/data/minio'
    networks:
      - backend

networks:
  backend:
    driver: bridge